### ISSUE TITLE
can not prerender it

### ISSUE THREAD

**Issue by iamike** [scaccogatto/vue-waypoint#7]
I am using vue-cli webpack, and when I trying to using prerender the project, it always get error.

```
WARNING: JavaScript error while prerendering: /home
ReferenceError: Can't find variable: Symbol

  phantomjs://code/phantom-page-render.js:26 in onError
```
please help, thanks

**Comment by scaccogatto** [comment]
Your error seems something related with some missing polyfill.
You should make sure:
1. Your code is correctly polyfilled, if not, try to prerender an empty Vue project with just a waypoint component and publish a working repo for testing purposes.
2. Check if [this update](https://github.com/scaccogatto/vue-waypoint/commit/e40ee70b5be136dfeffceb9dc74df03e01dbdd30) fixes the problem for you

**Comment by iamike** [comment]
Hi Scaccogatto,
Thanks for your advise, I have tried both 2 suggestion. I think that I am using a very neat environment.
You can reproduce this issue by the following step.
1. vue init webpack projectName,
2. npm install --save prerender-spa-plugin
3. check the /build/webpack.prod.conf.js file. and insert below two snip code into the var/plugins  section . finally it will be something look like this.

```
...
var PrerenderSpaPlugin = require('prerender-spa-plugin')
...
plugins: [
...
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
    ]),
    new PrerenderSpaPlugin(
      // Absolute path to compiled SPA
      path.join(__dirname, '../dist'),
      // List of routes to prerender
      [ '/' ]
    )
...
```
4. ensure prerender-spa-plugin working correctly, and router doesn't include any async component.(make it prerenderable 'Helloworld' without vue-waypoint)

5. npm install --save-dev vue-waypoint 
6. find src/main.js and just put below code into it. so we can globally use this plugin.

```
import VueWaypoint from 'vue-waypoint'
Vue.use(VueWaypoint)
``` 


7. npm run build,  and error occur at here.

```
> test@1.0.0 build /Users/Mike/Documents/vuejs/test
> node build/build.js

⠋ building for production...(node:45622) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
⠸ building for production...
Starting to optimize CSS...
Processing static/css/app.c944a78bbe87375c7bc8836b27b23e02.css...
Processed static/css/app.c944a78bbe87375c7bc8836b27b23e02.css, before: 431, after: 363, ratio: 84.22%
⠴ building for production...
/Users/Mike/Documents/vuejs/test/node_modules/prerender-spa-plugin/lib/compile-to-html.js:80
                    if (error) throw stdout
                               ^
WARNING: JavaScript error while prerendering: /
ReferenceError: Can't find variable: Symbol

  phantomjs://code/phantom-page-render.js:26 in onError

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Mike/.npm/_logs/2017-07-20T12_38_25_403Z-debug.log
```
the npm debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.3.0
3 info using node@v7.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle test@1.0.0~prebuild: test@1.0.0
6 info lifecycle test@1.0.0~build: test@1.0.0
7 verbose lifecycle test@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle test@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Mike/Documents/vuejs/test/nod$
9 verbose lifecycle test@1.0.0~build: CWD: /Users/Mike/Documents/vuejs/test
10 silly lifecycle test@1.0.0~build: Args: [ '-c', 'node build/build.js' ]
11 silly lifecycle test@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle test@1.0.0~build: Failed to exec build script
13 verbose stack Error: test@1.0.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid test@1.0.0
15 verbose cwd /Users/Mike/Documents/vuejs/test
16 verbose Darwin 16.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v7.8.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error test@1.0.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the test@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by scaccogatto** [comment]
Can you try this?
https://babeljs.io/docs/usage/polyfill/

`npm install --save-dev babel-polyfill`

then change your webpack config:
```
module.exports = {
  entry: ["babel-polyfill", "./app.js"]
};
```
(edit this with your app entry point)

**Comment by iamike** [comment]
it really fixed my problem. words can not express my happiness. Thanks!

**Comment by scaccogatto** [comment]
It would be great if you could send a pull request editing the README file explaining that this plugin requires a very modern browser or a complete polyfill. Glad that helped you.
