### ISSUE TITLE
Nuxt 3 - window is not defined

### ISSUE THREAD

**Issue by Dollique** [scaccogatto/vue-waypoint#82]
I am using a fresh setup of nuxt 3 and always get the error `window is not defined`

Full error message:

```
500
window is not defined
at callWithErrorHandling (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:156:18)
at setupStatefulComponent (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7190:25)
at setupComponent (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7151:36)
at renderComponentVNode (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:614:15)
at Module.ssrRenderComponent (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:86:10)
at _sfc_ssrRender (C:\Users\USER\sites\nuxt3_test\app.js:26:31)
at renderComponentSubTree (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:683:9)
at renderComponentVNode (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:631:12)
at Module.ssrRenderComponent (C:\Users\USER\sites\nuxt3_test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:86:10)
```

**package.json**

```
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^18.17.3",
    "nuxt": "^3.6.5"
  },
  "dependencies": {
    "vue-waypoint": "^4.2.5"
  }
}
```

I created the following file: `plugins/vue-waypoint.client.js`. The `.client` part should make sure it's run on client-side only

```
import { Waypoint } from "vue-waypoint";

export default defineNuxtPlugin((nuxtApp) => {
  if (process.client) {
    nuxtApp.vueApp.use(Waypoint);
  }
});
```

And used your code from the documentation in my `app.vue`

```
<template>
  <Waypoint @change="onChange">
    <!-- anything you want here -->
  </Waypoint>
</template>

<script lang="ts">
import { Waypoint } from "vue-waypoint";

export default defineComponent({
  name: "SomeComponent",
  components: {
    Waypoint,
  },
  setup() {
    const onChange = (waypointState) => {
      // Going can be:
      // IN
      // OUT
      console.log(waypointState.going);

      // Direction can be:
      // UP
      // DOWN
      // LEFT
      // RIGHT
      console.log(waypointState.direction);
    };

    return { onChange };
  },
});
</script>
```

**Comment by Dollique** [comment]
Just noticed the PR #77 to add SSR request.
I tested it and it solves my issue.

Please accept the PR and release a new version.
